version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory:  ~/cache-stampede # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose -p stampede up -d
      - run: mkdir .docker_node_modules || true
      - run: npm test
      - store_artifacts:
          path: coverage/lcov-report