version: "4"

# Bump the client image version HERE when changing Dockerfile

services:
  runner:
    image: cache-stampede-runner:1
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
      - redis
      - dynamodb
    links:
      - mongodb
      - redis
      - dynamodb
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
     - ./.docker_node_modules:/usr/src/app/node_modules:Z
    command: sh -c 'tail -f /dev/null'

  mongodb:
    image: 'mongo:6.0'

  redis:
    image: redis

  dynamodb:
    image: amazon/dynamodb-local