version: "3"

# IMPORTANT
# Make sure you run setup-docker.sh before executing this!!!
#
# Bump the client image version HERE when changing client/Dockerfile

services:
  runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
      - redis
      - dynamodb
    links:
      - mongodb
      - redis
      - dynamodb
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
     - ./.docker_node_modules:/usr/src/app/node_modules:Z
    command: sh -c 'tail -f /dev/null'

  mongodb:
    image: 'mongo:3.2.17'

  redis:
    image: redis

  dynamodb:
    image: amazon/dynamodb-local